### ISSUE TITLE
aobut model weights

### ISSUE THREAD

**Issue by boozyguo** [yashasvi97/IJCB2020_anomaly#1]
hello, could you provide the model weights?
thank you.

**Comment by yashasvi97** [comment]
Hello @boozyguo, I have released models in a pre-release. Let me know if you have any doubts.
Thanks!

**Comment by boozyguo** [comment]
Thank you @yashasvi97.  I can't find the downloaded link of models, so could you give me the link? Thank you.

**Comment by notha99y** [comment]
@boozyguo https://github.com/yashasvi97/IJCB2020_anomaly/releases/tag/v1.0-replay try this

**Comment by yashasvi97** [comment]
Hi, @notha99y thanks for adding the answer. @boozyguo you may download the file and from the above link. Once downloaded you can create `models/EXP_NAME/` folder and put the downloaded models in that location just so to follow code structure. Hope this helps! 
Thanks!
